name = "EHTUtils"
uuid = "9d0fa6a6-ae25-4c2e-8152-6c4b7f2016aa"
authors = ["Kazu Akiyama"]
version = "0.1.0"

[compat]
julia = "1.7.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
